### ISSUE TITLE
Only file in FIDVC zip folder is README.md

### ISSUE THREAD

**Issue by pewowaruk** [FranckLab/FIDVC#1]
Hello,

When I attempt to download the zip files for the FIDVC source code I don't get all of the necessary files.

At https://github.com/FranckLab/FIDVC/releases the source code zip only contains the file README.md which says to go to the above url to download the rest of the files.

**Comment by FranckLab** [comment]
Hello, 
We were just making a change in the code. You should be able to see the code online in few hours.

**Comment by FranckLab** [comment]
The codes have been updated.
