### ISSUE TITLE
Error in x, y, and z dimensions

### ISSUE THREAD

**Issue by MColasurdo** [FranckLab/FIDVC#10]
Hello again,

Have you performed any studies comparing the accuracy of the algorithm in the xy vs. z directions? Ideally, accuracy would be equivalent in all directions, but results of mine indicate that xy error is approximately 10-20% while z error is 30-40%. I suspect that this is likely due to the nature of reconstructing 3D volumes from slices in the z direction that results in lower accuracy in this direction. Have you made similar observations or is it possible that something may be wrong with my system? Thanks!

**Comment by mohakpatel** [comment]
The algorithm doesn't inherently have a bias for error in a particular direction. It is symmetric for all the directions (x,y and z). However, the issues come from the images being used. In confocal images, there is a larger spread in PSF in z-direction compared to x and y directions. Higher errors in z-direction will arise from the images, and not the algorithm itself. Deconvolving images to correct for PSF before using FIDVC will help you reduce errors in z-directions. 
How are you taking images? This might help figure out the source of error.
