### ISSUE TITLE
calculated surface

### ISSUE THREAD

**Issue by yclu1214** [FranckLab/FIDVC#11]
Hi,

I have some questions for using your code to convert my beads displacement into force.
First, I did fluorescent beads experiment with cell and observe the bead displacement by confocal microscope. But the number for the z-stack is 39 or 40. ( 8units in x_y=512_512) Could I used your code to process the images? 
Second, I have already calculate the bead displacement. Is it possible to use my current bead displacement in the FIDVC (just skip the first part) 
Thanks.

Best,
Jason

**Comment by mohakpatel** [comment]
Hi Jason, 
The displacements near borders are error prone, so we ask for input volumes to have at least 96 z -slices. You could FIDVC on your volumes with just 40 slices, but there will be errors in displacements in a z-direction. 

I don't understand your 2nd question. If you already have computed the bead displacement, what do you want to use FIDVC for?

Cheers,
Mohak

**Comment by yclu1214** [comment]
Hi Mohak,

Sorry, I posted a question in wrong one, I was asking in 3D-VTFM. I would like to use your code to convert my bead displacement into force. But I have some problem to use the code on my data.
Thanks.

Best,
Jason

**Comment by mohakpatel** [comment]
Okay, so what issue are you having using the bead displacement with 3D-VTFM?

**Comment by mohakpatel** [comment]
Also, it will be great if we can continue this conversation on the issues page of 3D-VTFM?
