### ISSUE TITLE
Problem regrding boundary of the image

### ISSUE THREAD

**Issue by Erfan453** [FranckLab/FIDVC#14]
Dear sir,

To check your software for my experiment images, I wrap my image with known displacement field to create the stressed image. Then I compare the displacement field with what I applied. My image is a sphere under uniform expansion ( 400 pa). 
Your software perfectly matched the distorted image with initial one.  But there is a problem on the boundary of sphere. As you can see in the attached pictures, the stress should be 400 pa within the sphere, but there is an significant error on the edges ( you can see the surface plot of the displacement, and the its gradient is different near the boundary due to interpolation) . Since I want the traction, this has caused serous problem for me. (I just attached the middle xy stack for representation)

The first image is the actual and distorted image under uniform expansion
The second image is showing the good match after iterations
The forth is comparison of the actual and FIDVC displacement.
The fifth one showed sigmaxx and the red dots is the periphery of sphere in the middle section.
I really appreciate if you help me to mitigate this issue. I f you think sending my data will help, please let me know.

Thanks in advance
Yours sincerely

![1](https://cloud.githubusercontent.com/assets/21693418/21707483/2880b01e-d395-11e6-9419-dfb024a6cb72.png)
![2](https://cloud.githubusercontent.com/assets/21693418/21707484/2c6e1766-d395-11e6-8857-c69f368b97bf.png)
![3](https://cloud.githubusercontent.com/assets/21693418/21707485/2e8a7c56-d395-11e6-9254-973edb5af898.png)
![4](https://cloud.githubusercontent.com/assets/21693418/21707487/30a023e2-d395-11e6-8297-97327ceaaeec.png)
![5](https://cloud.githubusercontent.com/assets/21693418/21707488/33485a56-d395-11e6-8a3c-a260222c8985.png)

**Comment by mohakpatel** [comment]
Hi, 
I'm Mohak Patel, a graduate student from Franck lab. 

I'm currently traveling on vacation.I will get back to you soon on this issue. Can you wait for a while? Please let me know. 

Best, 
Mohak

**Comment by Erfan453** [comment]
Hi,

Thanks for your response. Sure, I really appreciate your help.

Thank in advance
Yours sincerely
________________________________

**Comment by mohakpatel** [comment]
Hi Erfan, 

Thank you for waiting patiently. I'm back at work and can help you with your query. 

FIDVC is a DIC based tracking method, which tracks displacement by matching subsets of the images using cross-correlation. As a result, the displacement value near the border of the images is more error prone as the image subset gets cropped. This is one of the reasons why you have errors near the border of images. 

FIDVC for displacement measurement requires high contrast speckle pattern. From the raw images, it seems that the particle seeding density in the images is too low. Increasing the seeding density and decreasing particle size will help in improving the tracking performance of FIDVC.

These are two main reasons why I think you are getting errors with FIDVC. In any case, can you send me your raw images? It will help me look into the issue in detail. My email id is: patelbmohak@gmail.com

I hope this helps. 

Best,
Mohak
