### ISSUE TITLE
Rigid Registration Pre-Processing

### ISSUE THREAD

**Issue by MColasurdo** [FranckLab/FIDVC#15]
Does the FIDVC algorithm perform any rigid registration pre-processing to align the two volumes prior to their cross-correlation? If not, is this something that could/should be done prior to implementing FIDVC to enhance accuracy of FIDVC? Thanks!

**Comment by mohakpatel** [comment]
No, FIDVC does not do any rigid registration pre-processing. However, if the rigid displacement is small, registration in pre-processing step is not needed. 

The displacements result from FIDVC will have true displacement + rigid displacement added in them. An effective way to remove this rigid displacement is by subtracting each component of displacement with mean or median displacement.

I hope this helps. 

Best,
Mohak
