### ISSUE TITLE
3D TFM

### ISSUE THREAD

**Issue by MColasurdo** [FranckLab/FIDVC#16]
It seems that in most of Franck's publications, FIDVC is used with cells seeded atop 3D matrices containing the fluorescent beads. Is it also capable of resolving displacements with cells embedded within the 3D matrix among the fiduciary markers? Thanks!

**Comment by mohakpatel** [comment]
Yes, it can resolve displacements with cells embedded within 3D matrix among fiduciary markers. You can read about it in the following paper from our lab: http://www.pnas.org/content/113/11/2898.full
