### ISSUE TITLE
Parseinput

### ISSUE THREAD

**Issue by Taoooooooooooo** [FranckLab/FIDVC#18]
Hi,

I am trying to use FIDVC to calculate the deformation of displacements of two MRI images. However, I got confused when I started looking at the code. In the comments you mentioned inputs should be I, sSize, sSpacing and ccThreshold. However, in the code, you added m, mSize, MTF, M on top of what has already existed. Also, I what does parseinput represent? 

Thank you,

Tao

**Comment by mohakpatel** [comment]
Hi Tao, 
Almost all the functions have their own parseinput subfunction. So which particular parseinput subfunction are you referring too?

Best,
Mohak
