### ISSUE TITLE
Strain calculations, Total displacements from incremental analysis, and very small bug

### ISSUE THREAD

**Issue by nmlarson2** [FranckLab/FIDVC#19]
Hello, 

Thank you for the FIDVC code!

I have a few questions:
1. Do you have code to calculate strains from the displacement results?
2. Do you have code to calculate total cumulative displacements from the displacement results for incremental DVC? (I have to use incremental DVC because my first image and last image are very different. However, I would like to calculate the total cumulative displacement and strain for the last image. )
3. In exampleRunFile.m, I suggest correcting line 88 to: [~,h] = contourf(plotIdx{2}, plotIdx{1}, u{1}{i}(:,:,ceil(size(u{1}{i},3)/2)),25); colorbar
I used exampleRunFile.m on a rectangular data set, and found that I needed to make this correction due to the contourf input argument order.

Thank you, 
Natalie

**Comment by mohakpatel** [comment]
Hi Natalie, 

1. Yes, we have code to calculate strains from displacement results. Take a look at following code in our LD-3D-TFM package: https://github.com/FranckLab/LD-3D-TFM/blob/master/Matlab%20Code/fun3DTFM.m
It has all the functions required to compute deformation gradient (calculateFij), infinitesimal strain (funCalculateeij)and lagrangian strain (funCalculateLagrangianEij). It also has the gradient computation function (gradientN) and kernel to differentiate (fspecialSeperable). 

2. We are developing a 3D version of code to convert incremental displacements to cumulative displacements. We will be publishing it online soon (1-2 months). But I could potentially give you an early release version of it. 

3. Thanks for pointing out this bug. We will update our codes. 

Best,
Mohak

**Comment by nmlarson2** [comment]
Hi Mohak, 

Thank you for your quick response! Here are my responses and another question with the same number scheme:

1. Thank you; I'll check out your LD-3D-TFM package. 

2. I would greatly appreciate an early release version of your code to to convert incremental displacements to cumulative displacements! I will send you a separate email.

3. Thanks!

4. I would like to confirm the directions of the axes (x, y, and z) with respect to the 3D matrix indices. Is my attached diagram correct?

Thank you, 
Natalie

![coordinate_system_for_fidvc](https://user-images.githubusercontent.com/9683331/33403877-f368068c-d516-11e7-880f-ea34d15f4be7.jpg)

**Comment by FranckLab** [comment]
We addressed this issue via email, so I am closing this issue.

**Comment by alessiaperilli** [comment]
Hello,
I was interested in the 3D version of the code to convert incremental displacements to cumulative displacements, has it been published in the end? 
Thank you.
Alessia

**Comment by ALandauer** [comment]
Hi there,
Sorry for the delay - seems like there's a gap in coverage of the Franck lab GitHub since those of us who were supporting most of these codes have graduated in the last few years.  In any case, we haven't updated FIDVC itself to support this, but my beta-release port of the qDIC package to 3D, "qFIDVC", has the cumulation script included, see https://github.com/FranckLab/qFIDVC. The core function is ``inc2cum.m``. Feel free to follow up here, in the qFIDVC repo, or with me directly if you have any issues. 

Regards,
Alex L
