### ISSUE TITLE
Parrallelization of the FIDVC

### ISSUE THREAD

**Issue by ragyei** [FranckLab/FIDVC#2]
Hello, 
I wanted to find out if the FIDVC code is parallelizable. 
I want to perform a correlation with the distance spacing of 1. This procedure 
takes about 21 hours for a 512 by 512 by 192 image volume. 
Is there any means where i code tweak the code t perform the correlation on 
multiple processors?
Thank you.
Ronald.

**Comment by mohakpatel** [comment]
Hi Ronald, 

The FIDVC code could possibly be parallelized, but we haven't done it. The main loop that could be looked at is the for loop in DVC.m at line 41. You will need to make changes in the code to make it run on parallel. Feel free to explore that route. 

However, I want to know why you require the subset spacing of 1? 
What we do is run FIDVC with subset spacing of 8 (the default option), and distances in between can be effectively interpolated. I would recommend you to use this approach. 

Best,
Mohak

Graduate Student
Franck Lab
