### ISSUE TITLE
Question towards the displacement grid positions (m)

### ISSUE THREAD

**Issue by FrankFR** [FranckLab/FIDVC#21]
Dear Sir or Madam,

I read the answer to the questions "Retrieving mesh" coordinates and "How do the coordinates in the displacement matrices, u{1}{1:3}, correlate to the coordinates of the original volume?", but I still don't quite get it.

Imagine I have a reference and deformed volume of size **256x256x256**.
After running FIDVC (output mesh spacing **dm=8** and **sSize = 64** ->87,5% overlap of the interrogation windows) the resulting displacement fields u{1,1}{1,1 to 1,4} will have a size of **33x33x33**  and like mohakpatel stated:  
1 : dm : size(I,1)+dm 
gives me the positions where the displacement is calculated as m = 1,9,17,25,...,257.

Now, the  grid position 257 is the center of the last interrogation window, but outside of my original volume?! 
Is this correct or am I minsinterpreting the positions where the displacement grid is calculated?

Regards,

Frank

**Comment by FrankFR** [comment]
I edited the first version of my question due to the fact that I think I understood parts of what I was asking before.

**Comment by ALandauer** [comment]
Hi Frank,
Basically, yes.  To reduce errors near the edges, while still getting some information from the DVC, the algorithm pads images and selects subset that may contain padded area.  In this case, a subset is centered at m=257; the subset will contain approximately half padding and half image content. For this reason, the information content of edge subsets is lower and we typically see a lot more noise in the resultant displacements.

**Comment by FrankFR** [comment]
Hello Alex,

thank you for the clarification. 

Regards, 
Frank
