### ISSUE TITLE
Incremental to cumulative displacements follow up 

### ISSUE THREAD

**Issue by ragyei** [FranckLab/FIDVC#26]
Hi, 
This is a follow up on the discussions made on issue 19 dated (Nov 28, 2017),  on the computation of cumulative strains from incremental displacements in FIDVC code. I will like to find out if the 3D version of code to convert incremental displacements to cumulative displacements has been developed.
Thank you.
Ragyei.

**Comment by mohakpatel** [comment]
Hi Ragyei, 

Here is the code to convert incremental displacements to cumulative displacement:
https://github.com/FranckLab/qFIDVC/blob/master/inc2cum.m

Hope this is helpful!

Cheers,
Mohak
