### ISSUE TITLE
question on the displacement "u" components

### ISSUE THREAD

**Issue by ghost** [FranckLab/FIDVC#5]
Hi, 

I have read the source code and the Bar-Kochba et al. paper. But I still have trouble in understanding what the output matrix "u" means in the results. 

I get that:
First column of u{1,1} = displacement in X-direction (it's a 65x65x25 double in the provided example FIDVC-2.mat)
Second column of u{1,1} = displacement in Y-directoin (it's a 65x65x25 double in example FIDVC-2.mat)
Third column of u{1,1} = displacement in Z-direction (it's a 65x65x25 double in the provided example FIDVC-2.mat)
Fourth column of u{1,1} =magnitude of displacement (it's a 65x65x25 double in the provided example FIDVC-2.mat)

However, I don't quite understand why the displacement in each direction has 3 variables (i.e. 65, 65, 25) in its matrix. Shouldn't it be just one column matrix in each direction? I would think that we calculated one displacement at each sub voxel, and this is split into 3 directions / component (single value in each). How does it end up to have 65x65x25 in each direction?

In any case, will be great if you can fully describe the resulting "u" matrix displacement in greater context. what are the meaning of these columns and individual components.

Many thanks in advance,

Cecilia

Post-doc
Geological Engineering
UW Madison

**Comment by mohakpatel** [comment]
Hi Cecilia, 

The output 'u' describes the displacement at a 3D point in volume. 'u' is structured in the following way. 
u{1,t} describes the displacement at t time point. 
u{1,1}{1,1}, u{1,1}{1,1} and u{1,1}{1,1} describes the x, y and z component of displacement at 1st time point.  u{1,1}{1,4} describes the magnitude of displacement at 1st time point. 

FIDVC computes displacements for 3D volume. Each point in a 3D volume is defined by 3 coordinates. 3D points in a volume can be generated using [meshgrid function](http://www.mathworks.com/help/matlab/ref/meshgrid.html), which creates a 3D array to indicate position of a point. This is why u{1,1}{1,1} (call it ux for convenience) is a 3D array/grid. Basically, each element in ux is x component of displacement, and it's position in the 3D array indicates the position in the initial 3D volume. 

I hope this helps. You can also further read about meshgrid function on Matlab's documentation to understand how data is structured for 3D position in Matlab. Let me know if you any question. 

Best,
Mohak

**Comment by ghost** [comment]
Hello Mohak,

Thanks so much for the quick response!
While trying to understand your detailed explanation,

I wonder if you meant 
"u{1,1}{1,1}, u{1,1}{1,**2**} and u{1,1}{1,**3**} describes the x, y and z component of displacement at 1st time point. u{1,1}{1,4} describes the magnitude of displacement at 1st time point."

instead of
"u{1,1}{1,1}, u{1,1}{1,1} and u{1,1}{1,1} describes the x, y and z component of displacement at 1st time point. u{1,1}{1,4} describes the magnitude of displacement at 1st time point."

Sorry for picking on this small detail, but this will help me to understand your response!

Many thanks once again,

Cecilia

**Comment by mohakpatel** [comment]
Sorry for the typo. You have it right. I meant {1,1}{1,1}, u{1,1}{1,2} and u{1,1}{1,3}.

**Comment by ghost** [comment]
Now i do understand about the displacement results.
Thanks so much Mohak!

**Comment by mohakpatel** [comment]
Great!
