### ISSUE TITLE
What is the range of strain/displacement in which FIDVC is most accurate?

### ISSUE THREAD

**Issue by MColasurdo** [FranckLab/FIDVC#9]
Hi guys,

What is the minimum and maximum strain/displacement FIDVC can accurately resolve? Do you have any results demonstrating the accuracy of FIDVC at various strains, for example, comparing what FIDVC estimated the displacement to be compared to what the true displacement was? Thanks!

**Comment by mohakpatel** [comment]
Yes, the details of it are in the FIDVC paper. The link for it is on the main page.

**Comment by MColasurdo** [comment]
Hello again,

Have you performed any studies comparing the accuracy of the algorithm in the xy vs. z directions? Ideally, accuracy would be equivalent in all directions, but results of mine indicate that xy error is approximately 10-20% while z error is 30-40%. I suspect that this is likely due to the nature of reconstructing 3D volumes from slices in the z direction that results in lower accuracy in this direction. Have you made similar observations or is it possible that something may be wrong with my system? Thanks!
